#!/usr/bin/env bash
#BSUB -P BIP214
#BSUB -W 12:00
#BSUB -q batch
#BSUB -nnodes 256
#BSUB -J finetune
#BSUB -o finetune.o%J
#BSUB -e finetune.e%J

activate_opence

export PYTHONUNBUFFERED=1
export HF_HOME=/gpfs/alpine/world-shared/bip214/affinity_pred/train
export TORCH_EXTENSIONS_DIR=/gpfs/alpine/world-shared/bip214/affinity_pred/train/build

module load cuda/10.2

OMP_NUM_THREADS=1 jsrun -r 1 -g6 -a 6 -c 42 python ../affinity_pred/finetune.py --deepspeed='ds_config_scale.json' --output_dir='./results' --num_train_epochs=20 --per_device_train_batch_size=16 --per_device_eval_batch_size=128 --warmup_steps=0 --learning_rate=3e-05 --weight_decay=0.0 --logging_dir='./logs' --logging_steps=1 --evaluation_strategy="epoch" --gradient_accumulation_steps=1 --fp16=True --fp16_opt_level="02" --run_name="seq_smiles_affinity" --seed=42
